name: Artefact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  run-python-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2

      - name:
        run: python hello.py

  create-artifact:
    need: run-python-file
    runs-on: ubuntu-latest
    steps:
      - name: Upload the artefact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
